# Use new container infrastructure to enable caching
sudo: false


# Do not choose a language; we provide our own build tools.
language: generic


# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/.stack-work


# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
      - unzip
      - xvfb


before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- export TASTY_QUICKCHECK_TESTS=3
-
- # install stack
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'


script:
- stack test --no-terminal --haddock --no-haddock-deps
